### ISSUE TITLE
Unable to use ServerPinger placeholders

### ISSUE THREAD

**Issue by HappyAreaBean** [HappyAreaBean/ServerPinger-PAPI-Expansion#1]
**Describe the bug**

**To Reproduce**
1. Install ServerPinger
2. Use %serverpinger_online_anyIP%
3. See error

**Expected behavior**
Show server status text.

**Error**
```
[02:31:25] [Craft Scheduler Thread - 0/WARN]: Exception in thread "Craft Scheduler Thread - 0" 
[02:31:25] [Craft Scheduler Thread - 0/WARN]: org.apache.commons.lang.UnhandledException: Plugin PlaceholderAPI v2.11.1 generated an exception while executing task 362
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at cc.happyareabean.papiexpansion.pinger.lib.dns.Lookup.<clinit>(Lookup.java:36)
	at cc.happyareabean.papiexpansion.pinger.lib.mcserverping.MCPing.getPing(MCPing.java:81)
	at cc.happyareabean.papiexpansion.pinger.Pinger.fetchData(Pinger.java:110)
	at cc.happyareabean.papiexpansion.pinger.PingerExpansion$1.run(PingerExpansion.java:95)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 4 more
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 10 more

[02:31:26] [Craft Scheduler Thread - 4/WARN]: Exception in thread "Craft Scheduler Thread - 4" 
[02:31:26] [Craft Scheduler Thread - 4/WARN]: org.apache.commons.lang.UnhandledException: Plugin PlaceholderAPI v2.11.1 generated an exception while executing task 362
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class cc.happyareabean.papiexpansion.pinger.lib.dns.Lookup
	at cc.happyareabean.papiexpansion.pinger.lib.mcserverping.MCPing.getPing(MCPing.java:81)
	at cc.happyareabean.papiexpansion.pinger.Pinger.fetchData(Pinger.java:110)
	at cc.happyareabean.papiexpansion.pinger.PingerExpansion$1.run(PingerExpansion.java:95)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 4 more
```

**ServerPinger version: (/papi info serverpinger)**
2.3

**What server software are you using: (Please provide all the relevant information, include link, etc.)**
[Light Spigot Lite](https://www.mc-market.org/resources/16933/)

**Additional context**

**Comment by HappyAreaBean** [comment]
Fixed at v2.3.1
